[server]
port="9000"
addr="localhost"
readTimeout=5
writeTimeout=5
closeTimeout=5
csrf_protect="32-byte-long-auth-key"
env="development"
static_dir="/Users/vasu/Desktop/work/leanafy-management-panel/src/static/"

[logger]
file="log.log"
level="debug"

[database]
type="mongodb"
host="localhost"
dbName="parking_lot"
userName=""
password=""
connectionString="mongodb+srv://admin_pg:pg1234@pgcluster.g4nlk.mongodb.net/parking_lot"


[cors]
allowed_origins=["http://localhost:9000"]
allowed_methods=["GET", "POST", "PATCH", "PUT", "DETELE", "OPTIONS"]
allow_credentials=true
allowed_headers=["*"]